### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by WhistleMaster** [ChristianKuehnel/plantgateway#14]
What config in Home Assistant are you using to display a plant like this ?

<img width="344" alt="screenshot" src="https://user-images.githubusercontent.com/1544568/29827332-fea2b6a8-8cd9-11e7-8dc5-22e424a28b4b.png">

With my config, I can only see "ok" or "problem" and have to click on that to see what the problem is.

Thanks !

**Comment by ChristianKuehnel** [comment]
Hey, that picture is outdated. During the merge of the "plant" component in HomeAssistant we changed the architecture a bit. The maintainers wanted to have ok/problem as status and the problem cause as attribute...

**Comment by WhistleMaster** [comment]
That's a shame... Thanks !

**Comment by ChristianKuehnel** [comment]
You can try to do something similar if you create a group of the plant component and all the sensor components. But I'm not aware that there is a way to display the type of problem in the overview...

**Comment by WhistleMaster** [comment]
This is what I did finally

<img width="484" alt="screen shot 2017-08-29 at 17 57 09" src="https://user-images.githubusercontent.com/1544568/29830804-85301c84-8ce3-11e7-955b-ed71f136779b.png">

Thanks !
