### ISSUE TITLE
Selecting bluetooth device

### ISSUE THREAD

**Issue by syphernl** [ChristianKuehnel/plantgateway#18]
I've been using this for some time now on a Pi downstairs. However, due to the range it isn't capable of reaching plants upstairs. Upstairs I have an RPI W Zero with additional bluetooth USB stick (since the primary/onboard bluetooth is being used for constant polling). 

I'd like to install Plantgateway on this pi as well and make it use the second bluetooth stick in the system. However, looking trough the config and code I couldn't find a way to tell it which device to use.

Is this possible somehow?

**Comment by ChristianKuehnel** [comment]
**Now** it is possible :smile: I just added the parameter ```interface: 1``` to the config file. With this parameter you can select which Bluetooth interface shall be used by the plantgateway...

It's in the latest release https://github.com/ChristianKuehnel/plantgateway/releases/tag/0.4.0

**Comment by syphernl** [comment]
Awesome, thanks for adding this so quickly! Now only I have to figure out how to fix #15 so I can actually use it 😄

**Comment by syphernl** [comment]
Works like a charm!

**Comment by ChristianKuehnel** [comment]
You're welcome 😄
