### ISSUE TITLE
Select bluetooth

### ISSUE THREAD

**Issue by moskovskiy82** [ChristianKuehnel/plantgateway#20]
In the config file there is an option of selecting but...
Although i have set interface 1 it still connects via the interface 0 
There are no /dev/hci0 or /dev/hci1 devices
Although i see both interfaces under bluetoothctl

It's an octoprint release

**Comment by ChristianKuehnel** [comment]
Hi @moskovskiy82 ,

I just checked the code and the option should be forwarded correctly to the bluepy library. So I'm not sure what goes wrong there...

So to pin down the problem:
- Which version are you running? From pypi? Or a branch from github?
- Can you please turn on the debug mode in the config file and attach the log output.

**Comment by ChristianKuehnel** [comment]
old ticket --> closing it
