### ISSUE TITLE
Failed to connect to peripheral

### ISSUE THREAD

**Issue by brianhanifin** [ChristianKuehnel/plantgateway#21]
I'm trying to run Plant Gateway on a Raspberry Pi Zero W on Raspbian Lite. I installed using the `pip` command. I enabled debug mode and copied and pasted the tail end of my log file. I'd appreciate any advice you may have on connecting. BTW, I replaced the battery a few weeks ago and have it sitting 3 feet from the Pi. When I pop the battery out and replace it the LED on top of the Mi Flora starts flashing. Plus I got the mac address from... I forget the command (hcitool scan?). Thank you.

Here is the partial log file:
https://gist.github.com/brianhanifin/45e439b8b9b3bde3fcedcbc5876e466f

**Comment by jagter** [comment]
> I'm trying to run Plant Gateway on a Raspberry Pi Zero W on Raspbian Lite. I installed using the `pip` command. I enabled debug mode and copied and pasted the tail end of my log file. I'd appreciate any advice you may have on connecting. BTW, I replaced the battery a few weeks ago and have it sitting 3 feet from the Pi. When I pop the battery out and replace it the LED on top of the Mi Flora starts flashing. Plus I got the mac address from... I forget the command (hcitool scan?). Thank you.
> 
> Here is the partial log file:
> https://gist.github.com/brianhanifin/45e439b8b9b3bde3fcedcbc5876e466f

Which bluez version did you installed? I fixed the issue with the following steps:
* Installed bluez from source (version in repo has some vulnerabilities)
  * copy attrib/gatttool to /usr/bin (or /usr/local/bin)
* From the bluez source directory:
  - sudo tools/btmgmt le on
  - sudo tools/btmgmt connectable on
  - sudo tools/btmgmt power on
* sudo hciconfig hci0 down && sudo hciconfig hci0 up
* Ensure python3 is installed

Test with gatttool: /usr/bin/gatttool -B AA:BB:CC:DD:EE:FF -I

**Comment by ChristianKuehnel** [comment]
closing old ticket
