### ISSUE TITLE
Setting up cronjob

### ISSUE THREAD

**Issue by h4nc** [ChristianKuehnel/plantgateway#27]
Everything works perfect, got all my data in Home Assistant.

However I need some help setting up the cronjob (as I have no experience in doing that).

in `crontab -e` I pasted this line (just for testing every minute)

`*/1 * * * * plantgateway`

So this should run the tool every minute but it does not

I also tried

`*/1 * * * * /home/pi/plantgateway`

`*/1 * * * * /plantgateway`

What do I do wrong?

**Comment by ChristianKuehnel** [comment]
Are there any error messages from cron in your `/var/log/syslog`?

You can get the proper path for the executable by running  `where plantgateway` on the console.

**Comment by h4nc** [comment]
I can find these related error messages in syslog:

```
Oct 31 22:00:01 raspberrypi CRON[1021]: (pi) CMD (/home/pi/plantgateway)
Oct 31 22:00:01 raspberrypi CRON[1017]: (CRON) info (No MTA installed, discarding output)
Oct 31 22:01:01 raspberrypi CRON[1033]: (pi) CMD (/home/pi/plantgateway)
Oct 31 22:01:01 raspberrypi CRON[1029]: (CRON) info (No MTA installed, discarding output)
```

`where plantgateway` returns the following error 
-bash: where: command not found

**Comment by ChristianKuehnel** [comment]
Oh sorry, it's `which plantgateway` on Linux. where is for Windows...

**Comment by h4nc** [comment]
Than you, this was helpful, so in my case this is the line I had to add to cron

`0 * * * * /usr/local/bin/plantgateway`

**Comment by JDunnio** [comment]
Would be great to have this one line in the install manual

**Comment by ChristianKuehnel** [comment]
Feel free to create a PR to improve the documenation.
