### ISSUE TITLE
How to set retain flag

### ISSUE THREAD

**Issue by h4nc** [ChristianKuehnel/plantgateway#28]
When I restart home assistant the initial values of my plant sensors are unknown.

This first paragraph here 
https://www.home-assistant.io/components/sensor.mqtt/

>  If messages in this state_topic are published with RETAIN flag, the sensor will receive an instant update with last known value. 

tells us that the retain flag has to be set to avoid this.

Is it possible to set the retain flag in the configuration file?

**Comment by h4nc** [comment]
Retain flag is already set, has to be an issue with my config in ha.

**Comment by xbmcnut** [comment]
@h4nc Did you resolve your issue as I've just come across this today too?

**Comment by h4nc** [comment]
Yes, my values show up after a ha restart but to be honest I don't remember what solved this. 

I think adding `force_update: true` to my [mqtt sensor](https://www.home-assistant.io/integrations/sensor.mqtt/) configuration fixed it for me. Please let me know if this solves your issue too.

**Comment by xbmcnut** [comment]
Ah yes, `force_update`. That's the one! Thank you.
