### ISSUE TITLE
hassio addon

### ISSUE THREAD

**Issue by h4nc** [ChristianKuehnel/plantgateway#35]
Would be great to have this is an hassio addon.

**Comment by ChristianKuehnel** [comment]
HomeAssistant already comes with the `miflora` component. Why would you need plantgateway?

https://www.home-assistant.io/components/miflora/

**Comment by h4nc** [comment]
You're totally right. Plantgateway is about getting the bridge near to the plants if your ha instance is not near enough. 

Was a bit to fast with this idea, when I saw the new autodiscovery feature.
