### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by h4nc** [ChristianKuehnel/plantgateway#41]
What's new in 0.7.0 respectivly MiFlora 0.6? Do I need to update my sensors for that? 

Could you add some realese notes to the readme file?

**Comment by ChristianKuehnel** [comment]
The release notes are [here](https://github.com/ChristianKuehnel/plantgateway/releases). There are no release notes for miflora unfortunately. You can probably contact the owner of miflora for this...

**Comment by h4nc** [comment]
Ok, thanks. I won't contact the owner. Everything should be fine, if it is for you. 

And I can answer my own question. There is no need to update the sensors for v0.7.0. 

Current firmware version: v3.1.9
