### ISSUE TITLE
Still Active Project

### ISSUE THREAD

**Issue by adandl** [ChristianKuehnel/plantgateway#43]
Hello @ChristianKuehnel !

I'm looking to implement your plantgateway - looks very promissing and exactly what I need :)
Just wanted to make sure before I begin - is this project still active and up to date?
I'm planning to install on HomeAssistant 0.109

Kind regards from Austria

Albert

**Comment by ChristianKuehnel** [comment]
Well, I was using up until last month and I'm now moving to using [ESPHome](https://esphome.io/) on an ESP32. So it should still be usable, but I won't invest much effort at this point. It's also fairly easy to configure (and replace with something else).

**Comment by adandl** [comment]
ESPHome in combination with Mi Flora and home assistant?
That sounds even more interesting :-) - do you mind sharing your experience with this?
I'd really appreciate - you made me curious :)

Kind regards

Albert
